# Cohomology Ring and Asphericity of Real Parabolic Arrangements

This notebook demonstrates the computation of cohomology rings for complements of real parabolic arrangements, following the theory of
> J. Cantarero and J. L. León-Medina, *The Topology of Real Parabolic Arrangements*.

---

## Overview

Given a finite Coxeter group $(W, S)$ and a $W$-invariant collection $\mathscr{A}$ of parabolic cosets, we compute:

1. Betti numbers via cellular cohomology on the restricted permutahedron $K_{\mathscr{A}}$
2. The DGA structure: coboundary $\delta$ and cup product $\cup$ via the zonotopal (Serre) diagonal
3. Cup product span analysis (Baryshnikov generation)
4. Asphericity criteria: **flag condition** and **triangle-free** test on $\Gamma_{\mathscr{A}}$
5. A non-aspherical example in type $D_5$ where the flag condition fails and $H^2 \ne 0$

## 1. Load Module

In [25]:
load('../parabolic_arrangements.sage')

## 2. Minimal Example: $A_3$ (3-Equal Arrangement)

The **3-equal arrangement** in type $A_3$ excludes parabolic cosets $wW_I$ where $I$ contains a pair of non-commuting generators (i.e., $m_{st} \ge 3$). This is the simplest non-trivial case.

The restricted permutahedron $K_{\mathscr{A}}$ is the truncated octahedron with hexagonal faces removed.

In [26]:
# Build Weyl group and parabolic coset poset
W, Plist, _ = build_W_P('A', 3)

print(f"Weyl group: {W.cartan_type()}")
print(f"Order of W: {W.cardinality()}")
print(f"Total parabolic cosets: {len(Plist)}")

Weyl group: ['A', 3]
Order of W: 24
Total parabolic cosets: 75


In [27]:
# Define the 3-equal arrangement
Delta = ideal_k_parabolic(W, Plist, k=3)

print(f"Excluded cells: {len(Delta)}")
print(f"Cells in complement: {len(Plist) - len(Delta)}")

Excluded cells: 9
Cells in complement: 66


In [28]:
# Initialize the cohomology ring computation
arrangement = ParabolicArrangementCohomology(W, Plist, Delta)

print("\nCellular complex dimensions:")
for k in range(arrangement.max_grade + 1):
    n_k = len(arrangement.by_grade.get(k, []))
    print(f"  C^{k}: {n_k} cells")


Cellular complex dimensions:
  C^0: 24 cells
  C^1: 36 cells
  C^2: 6 cells


## 3. Betti Numbers

The cohomology $H^k(K_{\mathscr{A}}; \mathbb{F}_2)$ is computed as $\ker(\delta^k) / \operatorname{im}(\delta^{k-1})$.

In [29]:
print("Computing cohomology over F_2...\n")

betti_numbers = []
for k in range(arrangement.max_grade + 1):
    basis = arrangement.cohomology_basis(k, ring=GF(2))
    betti_numbers.append(len(basis))
    print(f"dim H^{k} = {len(basis)}")

print(f"\nBetti sequence: {tuple(betti_numbers)}")
print("Note: H^2 = 0 for A_3 (3-equal) — the arrangement is aspherical.")

Computing cohomology over F_2...

dim H^0 = 1
dim H^1 = 7
dim H^2 = 0

Betti sequence: (1, 7, 0)
Note: H^2 = 0 for A_3 (3-equal) — the arrangement is aspherical.


## 4. Verify DGA Structure

We verify that the coboundary operator and cup product satisfy the **graded Leibniz rule**:

$$\delta(u \cup v) = (\delta u) \cup v + (-1)^{|u|}\, u \cup (\delta v)$$

In [30]:
print("Verifying DGA structure...\n")
result = arrangement.verify_leibniz_rule(ring=GF(2), trials=10, use_fast=True)

if result:
    print("\nDGA structure verified!")
else:
    print("\nVerification failed!")

Verifying DGA structure...

--- Verifying DGA Leibniz Rule over Finite Field of size 2 ---
Testing degrees (1, 1)...
Leibniz Rule Verified: The DGA structure is consistent.

DGA structure verified!


## 5. Ring Structure for the $A_5$ (3-Equal) Arrangement

For the 3-equal arrangement in type $A_5$, the cohomology group $H^2$ is non-trivial. This allows us to investigate the ring structure.

Specifically, we will verify a result that follows from **Theorem 1** of Yuliy Baryshnikov's paper, *"On the cohomology ring of no k-equal manifolds"*. For these arrangements, the theorem implies that the cohomology ring $H^*$ is generated in degree 1. In our case, this means that $H^2$ should be completely generated by cup products of elements from $H^1$.

**Note**: This computation takes several seconds due to the size of the arrangement ($|W| = 720$).

In [31]:
print("Building A_5 (k=3) arrangement...")
W5, Plist5, _ = build_W_P('A', 5)
Delta5 = ideal_k_parabolic(W5, Plist5, k=3)
arrangement5 = ParabolicArrangementCohomology(W5, Plist5, Delta5)

print(f"\nOrder of W: {W5.cardinality()}")
print(f"Total parabolic cosets: {len(Plist5)}")
print(f"Cells in complement: {len(Plist5) - len(Delta5)}")

Building A_5 (k=3) arrangement...

Order of W: 720
Total parabolic cosets: 4683
Cells in complement: 3690


In [32]:
print("Computing cohomology over F_2...\n")

for k in range(min(3, arrangement5.max_grade + 1)):
    basis = arrangement5.cohomology_basis(k, ring=GF(2))
    print(f"dim H^{k} = {len(basis)}")

print("\nExpected Betti numbers: (1, 111, 20)")

Computing cohomology over F_2...

dim H^0 = 1
dim H^1 = 111
dim H^2 = 20

Expected Betti numbers: (1, 111, 20)


## 6. Cup Product via the Zonotopal Diagonal

The cup product is computed using the formula:

$$(u \cup v)(wW_I) = \sum_{J \sqcup K = I} \varepsilon(J,K) \cdot u(wW_J) \cdot v(w \cdot w_{0,J}\, W_K)$$

where $w_{0,J}$ is the longest element in $W_J$ and $\varepsilon(J,K)$ is the shuffle sign.

In [33]:
# Get basis of H^1 for A_5
H1_basis = arrangement5.cohomology_basis(1, ring=GF(2))

print(f"H^1 has {len(H1_basis)} generators")

if len(H1_basis) >= 2:
    u, v = H1_basis[0], H1_basis[1]
    
    print(f"\nComputing u_0 cup u_1...")
    print(f"  Support size of u_0: {u.hamming_weight()}")
    print(f"  Support size of u_1: {v.hamming_weight()}")
    
    product = arrangement5.fast_cup_product(u, v, 1, 1, ring=GF(2))
    
    print(f"\nProduct u_0 cup u_1:")
    print(f"  Support size: {product.hamming_weight()}")
    print(f"  Is zero: {product.is_zero()}")

H^1 has 111 generators

Computing u_0 cup u_1...
  Support size of u_0: 23
  Support size of u_1: 20

Product u_0 cup u_1:
  Support size: 4
  Is zero: False


### Cup Product Generation Analysis

Here, we test the main consequence of Baryshnikov's Theorem 1 for this specific arrangement. We compute the subspace of $H^2$ spanned by all pairwise cup products of basis vectors from $H^1$ and check if its dimension matches the dimension of $H^2$.

In [34]:
print("Analyzing cup product generation...\n")
result = arrangement5.cup_product_span_analysis(ring=GF(2), verbose=True)

print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)
print(f"H^2 dimension: {result['dim_H2']}")
print(f"Rank generated by products: {result['rank_generated']}")
print(f"Is complete: {result['is_complete']}")

if result['is_complete']:
    print("\nResult verified: H^2 is generated by H^1 products, as predicted by Baryshnikov's theorem.")
else:
    print(f"\nOnly {result['rank_generated']}/{result['dim_H2']} dimensions generated")

Analyzing cup product generation...

CUP PRODUCT SPAN ANALYSIS

Computing cohomology bases...
  dim(H^1) = 111
  dim(H^2) = 20

Precomputing cup structure for (1,1)...
Building projection matrix...

Analyzing 6105 pairs...
[Hit #1] Pair (10, 2) -> Rank 1/20
[Hit #2] Pair (24, 20) -> Rank 2/20
[Hit #3] Pair (27, 21) -> Rank 3/20
[Hit #4] Pair (30, 31) -> Rank 4/20
[Hit #5] Pair (90, 87) -> Rank 5/20
[Hit #6] Pair (92, 88) -> Rank 6/20
[Hit #7] Pair (95, 96) -> Rank 7/20
[Hit #8] Pair (105, 106) -> Rank 8/20
[Hit #9] Pair (3, 7) -> Rank 9/20
[Hit #10] Pair (8, 36) -> Rank 10/20
[Hit #11] Pair (49, 22) -> Rank 11/20
[Hit #12] Pair (6, 35) -> Rank 12/20
[Hit #13] Pair (32, 18) -> Rank 13/20
[Hit #14] Pair (33, 14) -> Rank 14/20
[Hit #15] Pair (89, 50) -> Rank 15/20
[Hit #16] Pair (97, 57) -> Rank 16/20
[Hit #17] Pair (98, 53) -> Rank 17/20
[Hit #18] Pair (107, 83) -> Rank 18/20
[Hit #19] Pair (108, 86) -> Rank 19/20
[Hit #20] Pair (109, 78) -> Rank 20/20

SUCCESS: H^2 fully generated in 23

## 7. Other Weyl Group Types

The theory and implementation work for all finite Coxeter groups. Here are Betti numbers for types $B_3$ and $D_4$.

In [35]:
# Type B_3 example
print("Type B_3 (hyperoctahedral group):")
WB, PlistB, _ = build_W_P('B', 3)
DeltaB = ideal_k_parabolic(WB, PlistB, k=3)
arrangementB = ParabolicArrangementCohomology(WB, PlistB, DeltaB)

for k in range(min(3, arrangementB.max_grade + 1)):
    basis = arrangementB.cohomology_basis(k, ring=GF(2))
    print(f"  dim H^{k} = {len(basis)}")

Type B_3 (hyperoctahedral group):
  dim H^0 = 1
  dim H^1 = 13
  dim H^2 = 0


In [36]:
# Type D_4 example
print("\nType D_4 (even signed permutations):")
WD, PlistD, _ = build_W_P('D', 4)
DeltaD = ideal_k_parabolic(WD, PlistD, k=3)
arrangementD = ParabolicArrangementCohomology(WD, PlistD, DeltaD)

for k in range(min(3, arrangementD.max_grade + 1)):
    basis = arrangementD.cohomology_basis(k, ring=GF(2))
    print(f"  dim H^{k} = {len(basis)}")


Type D_4 (even signed permutations):
  dim H^0 = 1
  dim H^1 = 73
  dim H^2 = 0


---

> **⚠️ Performance Warning.**
> The computations from this point onward involve the Coxeter group $D_5$ ($|W| = 1920$), which requires significantly more memory and CPU time than the earlier sections. **If you are running this notebook on Binder or a free cloud environment, the kernel is likely to hang or be killed.** We recommend executing Sections 8+ on a local installation of SageMath.

## 8. Failure of Asphericity and Indecomposable Classes

This section constructs the **minimal non-$W$-invariant truncation** that violates the flag condition, and computationally verifies every claim from the paper.

### Construction

Starting from the Coxeter group $D_5$ ($|W| = 1920$), we retain all strata of rank $\le 2$ together with the **right-angled** rank-3 types $\{1,4,5\}$ and $\{2,4,5\}$ (where all pairwise $m_{ij} = 2$). Every higher-rank stratum and every non-right-angled rank-3 stratum is removed.

The retained complex $K_{\mathscr{A}}$ should have **11,360 cells** (out of 12,483 total in the full permutahedron), distributed as:

$$C^0 = 1920, \quad C^1 = 4800, \quad C^2 = 4160, \quad C^3 = 480.$$

### Predictions

The paper predicts:
- The triple $\{1,2,3\}$ has all pairwise edges but no 2-simplex — the flag condition **fails**.
- $H^1 = 0$, $H^2 = \mathbb{Z}^{799}$, $H^3 = 0$.
- $\pi_1(\mathscr{M}_{\mathscr{A}}) = 1$ (trivial fundamental group).
- By Hurewicz: $\pi_2 \cong H_2 \ne 0$, so $K_{\mathscr{A}}$ is **not aspherical**.
- Since $H^1 = 0$, the cup product $H^1 \otimes H^1 \to H^2$ is trivially zero. All 799 classes in $H^2$ are **indecomposable**.
- **$W$-invariant comparison**: removing *all* rank$\,\ge 3$ strata gives $\dim H^2 = 1279$. Reintroducing the 480 right-angled rank-3 cells kills exactly 480 cycles: $1279 - 480 = 799$.

In [37]:
import time
from itertools import combinations

# Step 1: Build Coxeter system D_5
print("--- Step 1: Build Coxeter system D_5 ---")
t0 = time.time()

W_D5, Plist_D5, _ = build_W_P('D', 5)
S = sorted(W_D5.simple_reflections().keys())
n = len(W_D5)
cox = W_D5.coxeter_matrix()

print(f"  |W| = {n}")
print(f"  S = {S}")
print("  Coxeter matrix:")
for i in S:
    print(f"    {i}: {[int(cox[i, j]) for j in S]}")
print(f"  ({time.time() - t0:.1f}s)")

--- Step 1: Build Coxeter system D_5 ---
  |W| = 1920
  S = [1, 2, 3, 4, 5]
  Coxeter matrix:
    1: [1, 3, 2, 2, 2]
    2: [3, 1, 3, 2, 2]
    3: [2, 3, 1, 3, 3]
    4: [2, 2, 3, 1, 2]
    5: [2, 2, 3, 2, 1]
  (84.1s)


In [38]:
# Step 2: Build Delta (removal set)
print("\n--- Step 2: Build Delta ---")

def is_commutative(J_tuple):
    for a in range(len(J_tuple)):
        for b in range(a + 1, len(J_tuple)):
            if cox[J_tuple[a], J_tuple[b]] != 2:
                return False
    return True

rank3_types = list(combinations(S, 3))
ra_rank3 = [J for J in rank3_types if is_commutative(J)]
non_ra_rank3 = [J for J in rank3_types if not is_commutative(J)]
print(f"  Rank-3 types: {len(rank3_types)} total")
print(f"    RA (kept):     {ra_rank3}")
print(f"    non-RA (removed): {non_ra_rank3}")

Delta_D5 = set()
for c in Plist_D5:
    w, J = c
    J_sorted = tuple(sorted(J))
    rk = len(J_sorted)
    if rk <= 2:
        continue
    if rk == 3 and is_commutative(J_sorted):
        continue
    Delta_D5.add(c)

arr_D5 = ParabolicArrangement(W_D5, Plist_D5, Delta_D5)

total_cells = len(Plist_D5)
kept_cells = len(Plist_D5) - len(Delta_D5)

print(f"\n  Full permutahedron: {total_cells} cells")
print(f"  Removed:           {len(Delta_D5)}")
print(f"  K_A retained:      {kept_cells} cells")
for k in sorted(arr_D5.by_grade.keys()):
    print(f"    C^{k}: {len(arr_D5.by_grade[k])} cells")

# Verify paper's claimed cell counts
assert total_cells == 12483, f"Expected 12483 total, got {total_cells}"
assert kept_cells == 11360, f"Expected 11360 kept, got {kept_cells}"
expected_Ck = {0: 1920, 1: 4800, 2: 4160, 3: 480}
for k, expected in expected_Ck.items():
    actual = len(arr_D5.by_grade.get(k, []))
    assert actual == expected, f"C^{k}: expected {expected}, got {actual}"
print("\n  All cell counts match the paper.  ✓")


--- Step 2: Build Delta ---
  Rank-3 types: 10 total
    RA (kept):     [(1, 4, 5), (2, 4, 5)]
    non-RA (removed): [(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (2, 3, 4), (2, 3, 5), (3, 4, 5)]

  Full permutahedron: 12483 cells
  Removed:           1123
  K_A retained:      11360 cells
    C^0: 1920 cells
    C^1: 4800 cells
    C^2: 4160 cells
    C^3: 480 cells

  All cell counts match the paper.  ✓


### Flag Condition Check

We detect the flag violation by checking all triples of rank-1 types:
if all pairwise edges are present but the corresponding 2-simplex is missing,
the complex is **not flag**.

In [39]:
# Step 3: Check flag condition
print("--- Step 3: Check flag condition ---")

surviving_types = {}
for (w, J) in arr_D5.cells:
    rk = len(J)
    surviving_types.setdefault(rk, set()).add(J)

rank1_types = sorted(surviving_types.get(1, set()))
rank2_types = sorted(surviving_types.get(2, set()))
rank3_types_surv = sorted(surviving_types.get(3, set()))

print(f"  Rank-1 vertices: {rank1_types}")
print(f"  Rank-2 edges:    {rank2_types}")
print(f"  Rank-3 faces:    {rank3_types_surv}")

# Check all cliques
rank2_set = set(rank2_types)
rank3_set = set(rank3_types_surv)
flag_violations = []

for triple in combinations([t[0] for t in rank1_types], 3):
    triple_sorted = tuple(sorted(triple))
    edges_ok = all(
        tuple(sorted([triple_sorted[a], triple_sorted[b]])) in rank2_set
        for a in range(3) for b in range(a+1, 3)
    )
    if edges_ok and triple_sorted not in rank3_set:
        flag_violations.append(triple_sorted)

if flag_violations:
    print(f"\n  {len(flag_violations)} FLAG VIOLATIONS found:")
    for v in flag_violations:
        print(f"    {v}")
    print("\n  >> The link is NOT flag. Asphericity cannot be guaranteed.")
else:
    print("\n  No flag violations — arrangement may be aspherical.")

--- Step 3: Check flag condition ---
  Rank-1 vertices: [(1,), (2,), (3,), (4,), (5,)]
  Rank-2 edges:    [(1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]
  Rank-3 faces:    [(1, 4, 5), (2, 4, 5)]

  8 FLAG VIOLATIONS found:
    (1, 2, 3)
    (1, 2, 4)
    (1, 2, 5)
    (1, 3, 4)
    (1, 3, 5)
    (2, 3, 4)
    (2, 3, 5)
    (3, 4, 5)

  >> The link is NOT flag. Asphericity cannot be guaranteed.


In [40]:
# Also test with the built-in geometric criteria methods
print("\nUsing built-in methods:")
print(f"  is_triangle_free:    {arr_D5.is_triangle_free()}")
print(f"  check_flag_criterion: {arr_D5.check_flag_criterion()}")


Using built-in methods:
  is_triangle_free:    {'is_triangle_free': False, 'triangles': [(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (1, 4, 5), (2, 3, 4), (2, 3, 5), (2, 4, 5), (3, 4, 5)], 'graph': Graph on 5 vertices, 'is_Kpi1': None}
  check_flag_criterion: {'is_flag': False, 'violations': [(([ 0  0  0  0  1]
[ 0  0  0  1  0]
[ 0  0  1  0  0]
[ 0 -1  0  0  0]
[-1  0  0  0  0], ()), (1, 2, 3)), (([ 0  0  0  0  1]
[ 0  0  0  1  0]
[ 0  0  1  0  0]
[ 0 -1  0  0  0]
[-1  0  0  0  0], ()), (1, 2, 4)), (([ 0  0  0  0  1]
[ 0  0  0  1  0]
[ 0  0  1  0  0]
[ 0 -1  0  0  0]
[-1  0  0  0  0], ()), (1, 2, 5)), (([ 0  0  0  0  1]
[ 0  0  0  1  0]
[ 0  0  1  0  0]
[ 0 -1  0  0  0]
[-1  0  0  0  0], ()), (1, 3, 4)), (([ 0  0  0  0  1]
[ 0  0  0  1  0]
[ 0  0  1  0  0]
[ 0 -1  0  0  0]
[-1  0  0  0  0], ()), (1, 3, 5)), (([ 0  0  0  0  1]
[ 0  0  0  1  0]
[ 0  0  1  0  0]
[ 0 -1  0  0  0]
[-1  0  0  0  0], ()), (2, 3, 4)), (([ 0  0  0  0  1]
[ 0  0  0  1  0]
[ 0  0  1  0  0]
[ 0 -1  0  

### DGA Verification and Cohomology

We verify the DGA axioms and compute the cohomology ring over $\mathbb{F}_{32003}$.
The large characteristic avoids torsion artifacts.

In [41]:
# Step 4: Verify DGA
import sys
print("--- Step 4: Verify DGA properties ---")
ring = GF(32003)
t0 = time.time()

max_k = arr_D5.max_grade

# d^2 = 0
print("  Checking d^2 = 0...")
for k in range(max_k):
    nk = len(arr_D5.by_grade.get(k, []))
    nk1 = len(arr_D5.by_grade.get(k+1, []))
    if nk == 0 or nk1 == 0:
        print(f"    d^{k+1} d^{k}: trivial")
        continue
    dk1 = arr_D5.coboundary_matrix(k + 1, ring)
    dk = arr_D5.coboundary_matrix(k, ring)
    assert (dk1 * dk).is_zero(), f"d^2 != 0 at grade {k}"
    print(f"    d^{k+1} d^{k} = 0  ✓")

# Leibniz
leibniz_ok = arr_D5.verify_leibniz_rule(ring=ring, trials=30, use_fast=True)
print(f"  Leibniz rule: {'✓' if leibniz_ok else 'FAILED'}")

# Associativity
assoc_ok = arr_D5.verify_associativity(ring=ring, trials=30, verbose=False)
print(f"  Associativity: {'✓' if assoc_ok else 'FAILED'}")
print(f"  ({time.time() - t0:.1f}s)")

--- Step 4: Verify DGA properties ---
  Checking d^2 = 0...
    d^1 d^0 = 0  ✓
    d^2 d^1 = 0  ✓
    d^3 d^2 = 0  ✓
--- Verifying DGA Leibniz Rule over Finite Field of size 32003 ---
Testing degrees (1, 1)...
Testing degrees (1, 2)...
Testing degrees (2, 1)...
Leibniz Rule Verified: The DGA structure is consistent.
  Leibniz rule: ✓
  Associativity: ✓
  (16.6s)


In [42]:
# Step 5: Compute cohomology
print("\n--- Step 5: Compute cohomology ---")
t0 = time.time()

dims = {}
for k in range(max_k + 1):
    nCk = len(arr_D5.by_grade.get(k, []))
    if nCk == 0:
        dims[k] = 0
        print(f"  dim C^{k} = 0,  dim H^{k} = 0")
        continue
    Hk = arr_D5.cohomology_basis(k, ring)
    dims[k] = len(Hk)
    print(f"  dim C^{k} = {nCk},  dim H^{k} = {dims[k]}")

print(f"  ({time.time() - t0:.1f}s)")

# Verify paper's predicted cohomology dimensions
expected_Hk = {0: 1, 1: 0, 2: 799, 3: 0}
for k, expected in expected_Hk.items():
    if k in dims:
        assert dims[k] == expected, f"H^{k}: expected {expected}, got {dims[k]}"
print("\n  Cohomology dimensions match the paper.  ✓")


--- Step 5: Compute cohomology ---
  dim C^0 = 1920,  dim H^0 = 1
  dim C^1 = 4800,  dim H^1 = 0
  dim C^2 = 4160,  dim H^2 = 799
  dim C^3 = 480,  dim H^3 = 0
  (184.8s)

  Cohomology dimensions match the paper.  ✓


In [43]:
# Step 6: Cup product span analysis
print("\n--- Step 6: Cup product span analysis ---")
result_D5 = arr_D5.cup_product_span_analysis(ring=ring, verbose=True)


--- Step 6: Cup product span analysis ---
CUP PRODUCT SPAN ANALYSIS

Computing cohomology bases...
  dim(H^1) = 0
  dim(H^2) = 799

dim(H^1) = 0 < 2, cannot form products.


### Fundamental Group and the Hurewicz Argument

The paper proves $\pi_1(\mathscr{M}_{\mathscr{A}}) = 1$ for the $D_5$ arrangement.
By the Hurewicz theorem, when $\pi_1 = 1$ we have $\pi_2 \cong H_2$.
Since $H^2 = \mathbb{Z}^{799} \ne 0$, the complex $K_{\mathscr{A}}$ is **not aspherical**.

We verify $\pi_1 = 1$ via the CW 2-skeleton route (always valid, no $W$-invariance needed).

In [44]:
# Step 7: Compute pi_1 via CW 2-skeleton
print("--- Step 7: Fundamental group ---")
t0 = time.time()

arr_D5.init_pi1()
K_fp, _ = arr_D5.compute_pi1(method='cw', verbose=True)

is_trivial = bool(K_fp.IsTrivial())
print(f"\n  pi_1(M_A) is trivial: {is_trivial}")
assert is_trivial, "Expected pi_1 = 1 (trivial)"
print("  pi_1 = 1  ✓")

print(f"\n  Hurewicz: pi_1 = 1 and H^2 = Z^{dims[2]}")
print(f"  => pi_2 ≅ H_2 ≠ 0  =>  K_A is NOT aspherical  ✓")
print(f"  ({time.time() - t0:.1f}s)")

--- Step 7: Fundamental group ---
--- Building Complex of Groups ---
Subgroup H size: 1
Quotient Space Y has 11360 objects (orbits).
pi_1(K_A) -- CW 2-skeleton route
  Vertices (component): 1920
  Edges (component)   : 4800
  2-cells (component) : 4160
  Generators          : 2881
H_1(K_A; Z) = []

  pi_1(M_A) is trivial: True
  pi_1 = 1  ✓

  Hurewicz: pi_1 = 1 and H^2 = Z^799
  => pi_2 ≅ H_2 ≠ 0  =>  K_A is NOT aspherical  ✓
  (177.1s)


### $W$-Invariant Comparison: Accounting for the 799 Indecomposable Classes

We now verify the paper's counting argument. Start with the **$W$-invariant** truncation that removes *all* rank $\ge 3$ strata. This gives $\dim H^2 = 1279$.

Then re-introduce the 480 right-angled rank-3 cells (types $\{1,4,5\}$ and $\{2,4,5\}$). Each 2-cell kills exactly one 2-cycle, yielding $1279 - 480 = 799$ indecomposable classes.

Since $H^1 = 0$, the cup product $H^1 \otimes H^1 \to H^2$ is trivially zero — every class in $H^2$ is **indecomposable**.

In [45]:
# Step 8: W-invariant comparison (remove ALL rank >= 3)
print("--- Step 8: W-invariant comparison ---")
t0 = time.time()

Delta_full = set()
for c in Plist_D5:
    if len(c[1]) >= 3:
        Delta_full.add(c)

arr_full = ParabolicArrangement(W_D5, Plist_D5, Delta_full)

# Compute H^2 of the fully truncated arrangement
H2_full = arr_full.cohomology_basis(2, ring)
dim_H2_full = len(H2_full)

# Count the RA rank-3 cells we reintroduce
n_ra_cells = len(arr_D5.by_grade.get(3, []))

print(f"  Fully truncated (all rank >= 3 removed):")
print(f"    dim H^2 = {dim_H2_full}")
print(f"  RA rank-3 cells reintroduced: {n_ra_cells}")
print(f"  Expected: {dim_H2_full} - {n_ra_cells} = {dim_H2_full - n_ra_cells}")
print(f"  Actual dim H^2(K_A):          {dims[2]}")

assert dim_H2_full == 1279, f"Expected dim H^2 = 1279, got {dim_H2_full}"
assert n_ra_cells == 480, f"Expected 480 RA rank-3 cells, got {n_ra_cells}"
assert dim_H2_full - n_ra_cells == dims[2], \
    f"Arithmetic: {dim_H2_full} - {n_ra_cells} != {dims[2]}"
print(f"\n  1279 - 480 = 799  ✓")

print(f"\n  Since H^1 = 0, the cup product H^1 ⊗ H^1 → H^2 is trivially zero.")
print(f"  All {dims[2]} classes in H^2 are indecomposable.  ✓")
print(f"  ({time.time() - t0:.1f}s)")

--- Step 8: W-invariant comparison ---
  Fully truncated (all rank >= 3 removed):
    dim H^2 = 1279
  RA rank-3 cells reintroduced: 480
  Expected: 1279 - 480 = 799
  Actual dim H^2(K_A):          799

  1279 - 480 = 799  ✓

  Since H^1 = 0, the cup product H^1 ⊗ H^1 → H^2 is trivially zero.
  All 799 classes in H^2 are indecomposable.  ✓
  (128.8s)


### Summary: Failure of Asphericity in $D_5$

Every numerical claim from the paper has been verified computationally.

In [46]:
print("=" * 65)
print("  SUMMARY: D_5 NON-FLAG ARRANGEMENT")
print("=" * 65)
print(f"  Coxeter type:       D_5  (|W| = {n})")
print(f"  Full permutahedron: {total_cells} cells")
print(f"  K_A retained:       {kept_cells} cells")
print(f"  RA rank-3 kept:     {ra_rank3}")
print(f"  Flag violations:    {len(flag_violations)}: {flag_violations}")
print(f"  DGA:                {'VERIFIED' if leibniz_ok and assoc_ok else 'FAILED'}")
for k in sorted(dims):
    print(f"  dim H^{k} = {dims[k]}")
print(f"  Cup span rank:      {result_D5['rank_generated']} / {result_D5['dim_H2']}")
print(f"  pi_1(M_A):          {'trivial' if is_trivial else 'NON-TRIVIAL'}")
print(f"  W-inv comparison:   dim H^2 = {dim_H2_full} - {n_ra_cells} = {dims[2]}")
print()
print("  CONCLUSIONS:")
print(f"  1. H^2 = Z^{dims[2]} ≠ 0, pi_1 = 1")
print(f"     => pi_2 ≅ H_2 ≠ 0  =>  K_A is NOT aspherical  (Hurewicz)")
print(f"  2. H^1 = 0  =>  cup product H^1⊗H^1 → H^2 is zero")
print(f"     => all {dims[2]} classes in H^2 are indecomposable")
print(f"  3. W-invariant truncation: 1279 - 480 = 799")
print(f"     => RA rank-3 cells kill exactly 480 cycles")
print("=" * 65)

  SUMMARY: D_5 NON-FLAG ARRANGEMENT
  Coxeter type:       D_5  (|W| = 1920)
  Full permutahedron: 12483 cells
  K_A retained:       11360 cells
  RA rank-3 kept:     [(1, 4, 5), (2, 4, 5)]
  Flag violations:    8: [(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (2, 3, 4), (2, 3, 5), (3, 4, 5)]
  DGA:                VERIFIED
  dim H^0 = 1
  dim H^1 = 0
  dim H^2 = 799
  dim H^3 = 0
  Cup span rank:      0 / 799
  pi_1(M_A):          trivial
  W-inv comparison:   dim H^2 = 1279 - 480 = 799

  CONCLUSIONS:
  1. H^2 = Z^799 ≠ 0, pi_1 = 1
     => pi_2 ≅ H_2 ≠ 0  =>  K_A is NOT aspherical  (Hurewicz)
  2. H^1 = 0  =>  cup product H^1⊗H^1 → H^2 is zero
     => all 799 classes in H^2 are indecomposable
  3. W-invariant truncation: 1279 - 480 = 799
     => RA rank-3 cells kill exactly 480 cycles


---

## Summary

This notebook demonstrates:

1. **Cellular cohomology** of parabolic arrangement complements ($A_3$, $A_5$, $B_3$, $D_4$)
2. **DGA structure** verification (graded Leibniz rule)
3. **Cup product** computation via the zonotopal (Serre) diagonal
4. **Ring generation** for $k$-equal arrangements, verifying a result from Baryshnikov's work
5. **Asphericity failure** in $D_5$: the flag condition is necessary, and its violation produces $H^2 \ne 0$
6. **Fundamental group** $\pi_1 = 1$ via CW 2-skeleton, Hurewicz argument for non-asphericity
7. **Indecomposable classes**: all 799 generators of $H^2$ lie outside the image of the cup product
8. **$W$-invariant comparison**: $1279 - 480 = 799$ accounting for the effect of right-angled rank-3 cells

### Key result from the paper

---

**Version**: 3.0 | **Updated**: March 2026